### ISSUE TITLE
[Bug]: cant add blueprint

### ISSUE THREAD

**Issue by froniusMW** [SgtBatten/HA_blueprints#103]
### Description

Unknown error when adding blueprint. Tried differnt machines and waited a couple days. Still unknown error, importing other blueprints work fine. 

### Version

None

### Automation Config

```yaml
None
```

### Any other relevant information

```yaml
Logger: homeassistant.components.websocket_api.http.connection
Source: components/blueprint/importer.py:168
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 10:47:46 (1 occurrences)
Last logged: 10:47:46

[140146474870336] Error handling message: Unknown error (unknown_error) Gustav from 192.168.0.116 (Mozilla/5.0 (Linux; Android 13; SM-A226B Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/117.0.0.0 Mobile Safari/537.36 Home Assistant/2023.9.2-11226 (Android 13; SM-A226B))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/blueprint/websocket_api.py", line 76, in ws_import_blueprint
    imported_blueprint = await importer.fetch_blueprint_from_url(hass, msg["url"])
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/blueprint/importer.py", line 257, in fetch_blueprint_from_url
    imported_bp = await func(hass, url)
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/blueprint/importer.py", line 168, in fetch_blueprint_from_github_url
    resp = await session.get(import_url, raise_for_status=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 643, in _request
    resp.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 1005, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('https://raw.githubusercontent.com/SgtBatten/HA_blueprints/main/Frigate+Camera+Notifications/Stable')
```

**Comment by SgtBatten** [comment]
Where are you getting that url. It doesn't work.

**Comment by froniusMW** [comment]
From the import button, open the link in HA

**Comment by SgtBatten** [comment]
Hmm yes I see it too. I imported successfully only a few days ago so something has changed on HA end it seems. 

Maybe you can manually copy the url to the stable file and import still

**Comment by SgtBatten** [comment]
Yep manual import worked fine. 

I think HA is replacing %20 with + and it's breaking it.

**Comment by froniusMW** [comment]
That did it, thanks
